### ISSUE TITLE
Firefox Browser error

### ISSUE THREAD

**Issue by aeplatt** [oregon-historical-society/ohstasks#1]
Slideshows and OHP links on essay templates don't seem to be loading properly on Firefox. 

Check out Union page: https://oregonencyclopedia.org/articles/union/#.Wc6V7twsK2E

Tillamook Cheese: https://oregonencyclopedia.org/articles/tillamook_cheese/#.Wc6WMtwsK2E

**Comment by wylee** [comment]
Issues moved to oregon-historical-society/oregon-encyclopedia#7 and oregon-historical-society/oregon-encyclopedia#8.
